### ISSUE TITLE
Kirsty - lost work (you've begun sorting it)

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#192]
Submitter: Kirsty
Email: hinekuru@gmail.com
Novlr doesn't currently track the most recent changes - so if Novlr is already open in a tab (say - on a laptop in standby) - you do updates on a different computer, and then reopen that laptop - Novlr will instantly save the archived version over your recent changes rather than refreshing; so losing all your work.
There is also (as far as I can tell) no way to get those edits back - which has unfortunately just lost me 1000 words of work!

**Comment by kimberley-p** [comment]
replied:
Hi Kirsty,

I'm sorry to hear this. I'll look into getting your words back this evening from our backups. Could you help me by letting me know about what time you opened your laptop that was on standby (ie. the time you lost the words?). I'll see if I can retrieve them. It would also be helpful to know roughly what they were, for example, "the second half of the chapter called "my favourite chapter"."

We are currently looking at a way to recognise if Novlr is open in more than one place so that you can continue on and not worry about what point the other tab was at. We will definitely have that in the full release but even now in beta we are trying to get this and offline editing in place as soon as possible.

For current use until we have this, Novlr only saves when you type. So if you come to Novlr in a tab on another device that hasn't got the most recent version, refreshing will bring you your latest copy. Best practice though would be to close Novlr before using it in another device (we want you not to have to even think about that though which is why we will have the functionality very soon).

I'll get back to you this evening after digging around.

Thanks, 
Kim

**Comment by thomasmuirhead** [comment]
Kirsty replied - I replied to her:

Thanks for emailing! I'm so glad to hear you haven't had the problem again and that you're still using Novlr. And that you've reached a point where you're ready to export your work.

Yep, our priority is offline/multiple device stuff which is coming beginning of February and then we're tackling exporting.

Stay in touch - and we hope you keep enjoying using Novlr.

Thanks
